apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: private-registry
      containers:
      - name: backend
        image: 10.10.0.200:8082/demo-backend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MYSQL_DATABASE_HOST
          value: "mysql.default.svc.cluster.local"
        - name: MYSQL_DATABASE_PORT
          value: "51000"
        - name: MYSQL_DATABASE_USER
          value: "root"
        - name: MYSQL_DATABASE_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE_DB
          value: "simple"
        ports:
        - containerPort: 10000
          name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 51001
    nodePort: 30001
    targetPort: 10000
  selector:
    app: backend